name = "Typst"
grammar = "typst"
path_suffixes = ["typ", "typst"]
line_comments = ["// "]
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
tab_size = 2
soft_wrap = "editor_width"
autoclose_before = ";:.,=}])>$+-*/^_&|"
autoclose_escape_character = "\\"
brackets = [
    { start = "/*", end = " */", close = true, newline = true, not_in = ["string", "comment", "raw"] },
    { start = "(", end = ")", close = true, newline = true, not_in = ["string", "comment", "raw"] },
    { start = "{", end = "}", close = true, newline = true, not_in = ["string", "comment", "raw"] },
    { start = "[", end = "]", close = true, newline = true, not_in = ["string", "comment", "raw"] },
    { start = "$", end = "$", close = true, newline = true, not_in = ["string", "comment", "raw", "math"] },
    { start = "`", end = "`", close = true, newline = false, surround = true, not_in = ["string", "comment", "raw", "math"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment", "raw"] },
    { start = "*", end = "*", close = true, newline = false, surround = true, not_in = ["string", "comment", "raw", "math"] },
    { start = "_", end = "_", close = true, newline = false, surround = true, not_in = ["string", "comment", "raw", "math"] },
]
unordered_list = ["- ", "+ "]
ordered_list = [{ pattern = "^(\\d+)\\. ", format = "{1}. " }]
remove_empty_list_marker = false

[overrides.math]
extend_list_on_newline = false

[overrides.raw]
extend_list_on_newline = false

[overrides.string]
extend_list_on_newline = false

[overrides.comment]
extend_list_on_newline = false
